import { Inter, Archivo_Black } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";


const inter = Inter({ subsets: ["latin"] });
const archivoBlack = Archivo_Black({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter} ${archivoBlack} antialiased`}
      >
        <main className="mx-auto container">

        {children}
        </main>
      </body>
    </html>
  );
}
